### PR TITLE
Add Toggle

### PR DESCRIPTION
**Pull request by aprius**
image
image

### CODE REVIEW

**Comment by aprius** [comment]
Thank you for creating a great plugin, but it still looks like it needs a lot of improvement. I added the toggle enable / disable GameObject feature directly on the Hierarchy, check it and consider merging it if possible.

**Comment by truongnguyentungduy** [comment]
Capture
You can use the middle mouse to quickly activate or deactivate the GameObject directly on the hierarchy window. Is creating a toggle really necessary?

**Comment by aprius** [comment]
> Capture
> You can use the middle mouse to quickly activate or deactivate the GameObject directly on the hierarchy window. Is creating a toggle really necessary?

I think using the middle mouse is a bit inconvenient and clicking on the object name doesn't seem intuitive, what do you think?

**Comment by truongnguyentungduy** [comment]
Hm, when I created it I thought a lot about this before. And it also doesn't bring much benefit and also takes up more space on the hierarchy. (Especially when the hierarchy becomes complicated when there are multiple gameobjects at different depths and tags, layers, and components are rendered)
Currently I want to spend more space to display one more information that is the "static" state of the gameobject, but I still don't know how to make it convenient and intuitive but does not take up too much space.
Regarding this requirement of you, I can add it as an optional feature that users can enable it in settings (I'm not sure about this as it could turn out to be a redundant feature. Besides, some of the code of this pull request needs to be edited before possible
merge) or I could add a Delegate to the OnGUI events of Hierarchy 2 so the developers could extend the features they wanted.

**Pull request closed without merging**
